//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centro_Preprocessing_Dev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Centro_Preprocessing_UNIQUE
    {
        public Nullable<int> SERIAL_NUMBER { get; set; }
        public int UNIQUE_ID { get; set; }
        public Nullable<int> SCHEDULE_ID { get; set; }
        public string SCHEDULE_NAME { get; set; }
        public Nullable<System.DateTime> SURVEY_DATE { get; set; }
        public Nullable<int> PATTERN_ID { get; set; }
        public Nullable<double> ROUTE_NUMBER { get; set; }
        public string ROUTE_NAME { get; set; }
        public string DIRECTION_NAME { get; set; }
        public string BRANCH { get; set; }
        public Nullable<System.DateTime> TRIP_START_TIME { get; set; }
        public string TIME_PERIOD { get; set; }
        public string SERVICE_PERIOD { get; set; }
        public Nullable<int> TRIP_NUMBER { get; set; }
        public Nullable<int> TRIP_KEY { get; set; }
        public Nullable<int> BLOCK_NUMBER { get; set; }
        public string BLOCK_KEY { get; set; }
        public string BLOCK_NAME { get; set; }
        public Nullable<int> RUN_NUMBER { get; set; }
        public string RUN_KEY { get; set; }
        public Nullable<int> VEHICLE_NUMBER { get; set; }
        public string VEHICLE_DESCRIPTION { get; set; }
        public Nullable<int> VEHICLE_SEATS { get; set; }
        public string GARAGE_NAME { get; set; }
        public string DIVISION_NAME { get; set; }
        public Nullable<int> OPERATOR_ID { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<int> SORT_ORDER { get; set; }
        public Nullable<int> STOP_ID { get; set; }
        public string MAIN_CROSS_STREET { get; set; }
        public string TRAVEL_DIRECTION { get; set; }
        public Nullable<short> TIMEPOINT { get; set; }
        public Nullable<double> SEGMENT_MILES { get; set; }
        public Nullable<System.DateTime> TIME_SCHEDULED { get; set; }
        public Nullable<System.DateTime> TIME_ACTUAL_ARRIVE { get; set; }
        public Nullable<System.DateTime> TIME_ACTUAL_DEPART { get; set; }
        public Nullable<double> DWELL_TIME { get; set; }
        public Nullable<double> RUNNING_TIME_ACTUAL { get; set; }
        public Nullable<int> PASSENGERS_ON { get; set; }
        public Nullable<int> PASSENGERS_OFF { get; set; }
        public Nullable<int> PASSENGERS_IN { get; set; }
        public Nullable<int> WHEELCHAIRS { get; set; }
        public Nullable<double> TIMEPOINT_MILES { get; set; }
        public Nullable<short> FIRST_LAST_STOP { get; set; }
        public Nullable<bool> MODIFIED_FLAG { get; set; }
        public Nullable<bool> To_Be_Deleted { get; set; }
        public Nullable<bool> QUALITY_CHECK { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
    }
}
